name: Build and Push SNMP Exporter

on:
  workflow_dispatch: { }
  push:
    branches: [ main ]
    paths:
      - 'snmp.yml'
      - 'Dockerfile'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t $REGISTRY/${{ env.IMAGE_NAME }}:latest .

      - name: Push image
        run: |
          docker push $REGISTRY/${{ env.IMAGE_NAME }}:latest
